### ISSUE TITLE
Christi's progress tracker

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#210]
Day-long tasks to update completion:
(INDIVIDUAL NOTES OF EACH TASK MAY BE IN THEIR OWN COMMENT 

NOT doing yet for 2.0
- [ ] Wither storm rework(another time)
- [ ] aether inf, disable inf spawns/ content for now
- [ ] any more structures
- [ ] all npcs yet
- [ ] multiblocked
- [ ] adding art to questbook
- [ ] 

nexus 
- [ ] 24. [ ] Sync all portal locations
- [ ] 25. [ ] Add juegadors remodels as a rp
- [ ] 26. [ ] Add a timer
- [ ] 27. [ ] Figure out logic of tping player, spawning despawning boss, etc
- [ ] 28. [ ] Implement said logic for all the bosses
- [ ] 29. [ ] Figure out shutting portal gates while in boss rush and unlocking them 3 at a time
- [ ] 30. [ ] Figure out unique rewards and how to give them for every gauntlet, possibly only give core on first completion
- [ ] 31. [ ] Make list of pdgamerules for nexus and have perma adventure mode in the dimension
- [ ] 32. [ ] Make the damn structure spawn:save the structures files, part 1(theres no way its not gonna take at least three days)
- [ ] 33. [ ] Make the damn structure spawn: figure out how to place at specific locations, part 2
- [ ] 34. [ ] Make the damn structure spawn: test every single coordinate and command block for said locations extensively to make sure every block is the same, part 3
- [ ] 35. [ ] Make the damn structure spawn: fix the inevitable bullshit, part 4

npcs
- [ ] 37. [ ] Add trades for half remaining npcs
- [ ] 38. [ ] Add trades for all remaining npcs
- [x] 39. [ ] Figure out npc quest tracking: learn how to have npcs trigger certain quests, part 1
- [ ] 40. [ ] Figure out npc quest tracking: find and implement a custom items mod, part 2
- [ ] 41. [ ] Figure out npc quest tracking: make entries in dialogue and unlocks for all npcs quests giving basic descs of each npc trades and locations as well, part 3
- [ ] 42. [ ] Figure out npc quest tracking: make each quest unlovk respective houses in Nexus dorms, part 4
- [ ] 43. [ ] Add custom items to quests for each npc ur gonna do it
- [ ] 44. [ ] Add random daily quests for village npcs?
- [ ] 45. [ ] Make npcs spawn in structures first third
- [ ] 46. [ ] Make npcs spawn in structures second third
- [ ] 47. [ ] Make npcs spawn in structures third third
- [ ] 48. [ ] Copy down all my final drafts of npc dialogue to docs so lore writers can have a final lookover
- [ ] 49. [ ] Add 2 npcs, their dialogue trades and/or quests to nexus
- [ ] 50. [ ] Add 2 npcs, their dialogue trades and/or quests nexus
- [ ] 51. [ ] Add 2 npcs, their dialogue trades and/or quests to nexus
- [ ] 52. [ ] Add 2 npcs, their dialogue trades and/or quests to nexus
- [ ] 53. [ ] Add a black market npc once you complete enough nexus quests
- [ ] 54. [ ] Add a auction npc once you complete enough nexus questst
- [ ] 55. [ ] Add an event for when you unlock all npc dorms using that one guys alien tower build to the nexus
- [ ] 56. [ ] Add a event where you talk to the nexus mind after completing boss rush(should track progress in questbook)
- [ ] 57. [ ] Add some cute vehicles you get schematics for from the hangar
- [ ] 58. [ ] Add functionality for greenhouse/forge area
- [ ] 59. [ ] Build 3 npc dorm rooms
- [ ] 60. [ ] Build 3 npc dorm rooms
- [ ] 61. [ ] Build 3 npc dorm rooms
- [ ] 62. [ ] Build 3 npc dorm rooms
- [ ] 63. [ ] Build 3 npc dorm rooms 
- [ ] 64. [ ] Build 3 npc dorm rooms

nexus
- [ ] 65. [ ] Add method to get to nexus by possibly having ruined time machine portal in the nexus structure?
- [ ] 66. [ ] Add nexus celestial skybox part 1: figuring out how celestial works and making assets
- [ ] 67. [ ] Add nexus celestial skybox part 2: making the pack
- [ ] 68. [ ] Add nexus celestial skybox part 3: testing in game

**ost**
- [ ] 69. [ ] Listen to emit remmus music for potential tracks 
- [ ] 71. [ ] Listen to ost and assign each song to a area second third
- [ ] 72. [ ] Listen to ost and assign each song to a area third third
- [ ] 73. [ ] Actually figure out how to implement said songs-mod from ethanicus

spawns
- [ ] 75. [ ] Figure out how to spawn mobs using incontrol instead of sbu
- [ ] 76. [ ] Set spawns for entirety of blue skies: unusual prehistory unusual fish namely
bs structures
- [ ] 77. [ ] Compile all the finished blue skies datapack structures into one datapack and test every single one(waiting on soul to make it fix lag issues add loot tables spawn weights biomes etc)

nexus stats
- [ ] 80. Tweak five nexus&base boss stats
- [ ] 81.Tweak five nexus&base boss stats
- [ ] 82.Tweak five nexus&base boss stats
- [ ] 83.Tweak five nexus&base boss stats
- [ ] 84.Tweak five nexus&base boss stats
- [ ] 85.Tweak five nexus&base boss stats
- [ ] 86.Tweak five nexus&base boss stats
- [ ] 87.Tweak five nexus&base boss stats
- [ ] 88.Tweak five nexus&base boss stats
- [ ] 89.Tweak rest of nexus&base boss stats

eye rework
- [x ] 90.  make each eye have a mechanic
- [ ] 91.  make each eye have a mechanic day 2

inv
- [ ] 92. inv overhaul mod

nexus
- [] 93. boss reskin gauntlet 5
- [] 94. boss reskin gauntlet 6
- [] 95. boss reskin gauntlet 7
- [] 96. boss reskin gauntlet 8
- [] 97. boss reskin gauntlet 9
- [] 98. boss reskin gauntlet 10

nerd
- [] 99. compile toxins sh & combine all content do last

cinematic trailer
- [] 100. juegador

1.6

- [ ] 1. fog shaders
- [ ] 2. remove pics questbook
- [ ] 3. stupid perf mods
- [ ] 4. compile 
- [ ] 5. added 

![Image](https://github.com/chocolate-edition/Chocolate-Edition/assets/103792572/2075b01d-d001-4321-80ac-6f8a755a6965)

![Image](https://github.com/chocolate-edition/Chocolate-Edition/assets/103792572/44c75692-f7f5-42f0-8769-27d02f6d1235)

**Comment by RichPrune** [comment]
Void blossom: possibly drain aquifer, add flowers to make it jungly, make stalagmites into stalactites so the cave looks like its arched above the void, mud bricks as terraria reference, reskin possibly like plantera maybe with a bit of fel soil

**Comment by RichPrune** [comment]
Nether gauntlet: 
Nether is a dimension that harbors souls after death
1. Soulsand valley: Previously blue aurora like garden that wither corrupted with malicious soul energy
2. Nether wastes: Previously toxic wastes that got heated and infused with enough soul energy to become netherrack
3. Crimson forest: once a regular mushroom that bore fruit, the crimson wart took over the nether once it evolved to survive extreme heat and carnage
4. Warped forest: Mushrooms that were corrupted by end leaking over into the nether
5. Basalt delta: once frozen underground heat crystal volcanos below that shattered into solar crystals and glowstone dust byproduct
6. Glowstone canyon: dust waste of nether attracted and taken by aether leaking over

**Comment by RichPrune** [comment]
1. Starbound Belt(Forge)
2. Jelly factory
3. Freezing Moons
4. Wormhole Nebula
5. Black Hole

**Comment by RichPrune** [comment]
Nexus Point:
ancient remnant - 
Leviathan - 
Corrupted Champion - deep dark ancient city rebuilt (deep dark regrowth mod?)
Ender Guardian - 
Harbinger - 
Ignis - 
???

**Comment by RichPrune** [comment]
Attack bank:
/summon cataclysm:abyss_blast_portal ~ ~10 ~
/summon bosses_of_mass_destruction:comet ~ ~10 ~
/summon cataclysm:void_vortex ~ ~10 ~

/summon cataclysm:void_howitzer ~ ~10 ~
/summon cataclysm:dimensional_rift ~ ~10 ~
/summon cataclysm:ignis_fireball ~ ~10 ~

**Comment by RichPrune** [comment]
Bounties- Fetch Quests(includes custom items, personal request)
Deals- Big quests (existing quests only, business deal)

**Comment by GildedToxin** [comment]
Closing this, it hasnt been touched in over nearly 7 months and is very out of date
